pipeline {
    agent none
    stages {
        stage('Build') {
		agent {
			docker {
				image 'androidsdk/android-31:latest'
			}
		}
            	steps {	
		        echo 'Create New Build'
		    	sh 'chmod +x gradlew'
		        sh './gradlew assembleDebug'
            	}
        }
	stage('Test') {
		agent {
			docker {
				image 'androidsdk/android-31:latest'
			}
		}
		steps {
			echo 'No tests for now'
			/*script {
				try {
					echo 'Testing Now'
		    			sh 'chmod +x gradlew'
                        		sh './gradlew clean test --no-daemon' //run a gradle task
                    		} finally {
                        		junit '**/build/test-results/test/*.xml' //make the junit test results available in any case (success & failure)
                    		}
               		 }*/
		}
	}
    }
}
