pipeline {
    agent none
    stages {
        stage('Build') {
            agent {
                docker {
                    image 'androidsdk/android-31:latest'
                }
            }
            steps {
		    	sh 'cd ~/Library/Android/sdk/build-tools/31.0.0 && mv d8 dx && cd lib  && mv d8.jar dx.jar'
		    	sh 'cd'
		        echo 'Create New Build'
		    	sh 'chmod +x gradlew'
		        sh './gradlew assembleDebug'
            }
        }
        stage('Test') {
            agent {
                docker {
                    image 'androidsdk/android-31:latest'
                }
            }
            steps {
			sh 'cd ~/Library/Android/sdk/build-tools/31.0.0 && mv d8 dx && cd lib  && mv d8.jar dx.jar'
		    	sh 'cd'
		    	echo 'Testing Now'
		    	sh 'chmod +x gradlew'
                    	sh './gradlew clean test --no-daemon'
            }
	        post {
                always {
                    	junit '**/build/test-results/test/*.xml'
                }
            }
	
        }
    }
}
